name: asdaf-workshop
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - python=3.11
  - ipykernel
  - ipywidgets
  - jupyterlab
  - numpy
  - pandas
  - matplotlib
  - eodag
  - xarray
  - rioxarray
  - folium
  - numba
  - geopandas
  - earthpy
  - tqdm
  - pip:
     - FastAPI[all]
